export const SENSOR_DESCRIPTIONS: Record<string, string> = {
  'AQI': 'Índice de Calidad del Aire, indicador global calculado a partir de los principales contaminantes medidos.',
  'AQI SPAIN': 'Índice de Calidad del Aire calculado según la normativa española.',
  'AQI_EPA': 'Índice de Calidad del Aire calculado según la normativa de la Agencia de Protección Ambiental de EE. UU. (EPA).',
  'Battery': 'Nivel de batería del dispositivo.',
  'Charge': 'Voltaje de carga de la batería del dispositivo.',
  'Dew Point': 'Punto de rocío: temperatura a la que el aire se satura de humedad y comienza a condensarse.',
  'Heat Index': 'Sensación térmica percibida, combina temperatura y humedad.',
  'Humidity ext': 'Humedad relativa del aire exterior.',
  'NO2 GCc': 'Concentración de dióxido de nitrógeno (NO2) en el aire.',
  'NO2 GCc AVG1H': 'Media de la concentración de NO2 en la última hora.',
  'NO2 GCc AVG24H': 'Media de la concentración de NO2 en las últimas 24 horas.',
  'O3 GCc': 'Concentración de ozono troposférico (O3) en el aire.',
  'O3 GCc AVG1H': 'Media de la concentración de O3 en la última hora.',
  'O3 GCc AVG8H': 'Media de la concentración de O3 en las últimas 8 horas.',
  'PM1': 'Concentración de partículas en suspensión de diámetro inferior a 1 micra.',
  'PM1 AVG1H': 'Media de la concentración de PM1 en la última hora.',
  'PM10': 'Concentración de partículas en suspensión de diámetro inferior a 10 micras.',
  'PM10 AVG1H': 'Media de la concentración de PM10 en la última hora.',
  'PM10 AVG24H': 'Media de la concentración de PM10 en las últimas 24 horas.',
  'PM10_AVG_daily': 'Media diaria de la concentración de PM10.',
  'PM2.5': 'Concentración de partículas en suspensión de diámetro inferior a 2,5 micras.',
  'PM2.5 AVG1H': 'Media de la concentración de PM2.5 en la última hora.',
  'PM2.5 AVG24H': 'Media de la concentración de PM2.5 en las últimas 24 horas.',
  'PM2.5_AVG_daily': 'Media diaria de la concentración de PM2.5.',
  'Pollen Index': 'Índice estimado de presencia de polen en el aire.',
  'Pressure': 'Presión atmosférica medida por el dispositivo.',
  'Signal': 'Nivel de señal de radio/celular del dispositivo (RSSI).',
  'Temp': 'Temperatura del aire medida por el sensor interno del dispositivo.',
  'Temp ext': 'Temperatura del aire medida por el sensor externo del dispositivo.',
  'W Speed AVG': 'Velocidad media del viento.',
  'W Speed MAX': 'Velocidad máxima (racha) del viento.',
  'W Vane AVG': 'Dirección media del viento (veleta), en grados respecto al norte.',
};

export const SENSOR_LABELS: Record<string, string> = {
  'AQI': 'AQI',
  'AQI SPAIN': 'AQI España',
  'AQI_EPA': 'AQI EPA',
  'Battery': 'Batería',
  'Charge': 'Voltaje de carga',
  'Dew Point': 'Punto de rocío',
  'Heat Index': 'Índice de calor',
  'Humidity ext': 'Humedad relativa',
  'NO2 GCc': 'NO2',
  'NO2 GCc AVG1H': 'NO2 (media 1 h)',
  'NO2 GCc AVG24H': 'NO2 (media 24 h)',
  'O3 GCc': 'O3',
  'O3 GCc AVG1H': 'O3 (media 1 h)',
  'O3 GCc AVG8H': 'O3 (media 8 h)',
  'PM1': 'PM1',
  'PM1 AVG1H': 'PM1 (media 1 h)',
  'PM10': 'PM10',
  'PM10 AVG1H': 'PM10 (media 1 h)',
  'PM10 AVG24H': 'PM10 (media 24 h)',
  'PM10_AVG_daily': 'PM10 (media diaria)',
  'PM2.5': 'PM2.5',
  'PM2.5 AVG1H': 'PM2.5 (media 1 h)',
  'PM2.5 AVG24H': 'PM2.5 (media 24 h)',
  'PM2.5_AVG_daily': 'PM2.5 (media diaria)',
  'Pollen Index': 'Índice de polen',
  'Pressure': 'Presión atmosférica',
  'Signal': 'RSSI 4G',
  'Temp': 'Temperatura interna',
  'Temp ext': 'Temperatura exterior',
  'W Speed AVG': 'Viento velocidad media',
  'W Speed MAX': 'Viento velocidad máxima',
  'W Vane AVG': 'Viento veleta',
};

